# GitLab CI to build cdfj and install it in Geomag Artifactory
#
# Most of the configuration is in pom.xml
# The authentication is in .m2/settings.xml
# To work, you need to set MVN_REPO_USER and MVN_REPO_PASS variables to
#   the login credentials to the Artifactory repository where the code
#   will be deployed

image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package deploy
  only:
    - master

