# GitLab CI to build cdfj and deploy it to BGS Nexus
#
# Most of the configuration is in pom.xml
# The Nexus authentication is in .m2/settings.xml
# To work, you need to set MVN_REPO_USER and MVN_REPO_PASS variables to
#   the login credentials to the Nexus repository where the code
#   will be deployed.

image: maven:3.6.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile
  artifacts:
    paths:
      - target/
      - .m2/repository/

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS package deploy
  only:
    - master

