# GitLab CI to build cdfj and install it in Geomag Artifactory
#
# Most of the configuration is in pom.xml
# The authentication is in .m2/settings.xml
# To work, you need to set MVN_REPO_USER and MVN_REPO_PASS variables to
#   the login credentials to the Artifactory repository where the code
#   will be deployed
# A keystore and trust store that are setup with the certificates to access
# the maven repositories in pom.xml are included in this project
# If additional maven repositories are added in pom.xml the truststore will have 
# to be updated. 
# Instructions on how to use SSL keys with maven repositories can be found in
# http://geomag_websites.glpages.ad.nerc.ac.uk/handover_documentation/SimonFlower/
# in the section Web Servers->Use of http and https here
#

image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Djavax.net.ssl.trustStore=./trust.jks -Djavax.net.ssl.trustStoreType=jks -Djavax.net.ssl.keyStorePassword=$KEYSTORE_PWD -Djavax.net.ssl.keyStore=./keyStore.p12 -Djavax.net.ssl.trustStorePassword=$TRUSTSTORE_PWD -Djavax.net.ssl.keyStoreType=pkcs12 "

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - echo "$MAVEN_CLI_OPTS"
    - echo "$MAVEN_OPTS"
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package deploy
  only:
    - petes_test
    - master

